WIP: MR-23: errors handling
ItmoDreamTeam/MyRest pull request #56
Opened 2020-12-18 11:25 UTC by KirillSmirnow

Resolves #23

2020-12-23 21:49 UTC, AlexIvchenko requested changes

2020-12-23 23:16 UTC, KirillSmirnow commented on server/src/test/kotlin/org/itmodreamteam/myrest/server/service/table/TableServiceTest.kt
> -        val initialInfo = TableInfo(101, null, 3)
Because of `@Max(100, message = "table.number-of-seats.incorrect")`

2020-12-26 08:06 UTC, KirillSmirnow commented on server/src/main/kotlin/org/itmodreamteam/myrest/server/error/ThrowableToErrorsConverterImpl.kt
> +            if (converter.throwableType.isAssignableFrom(throwable.javaClass)) {
YAGNI

2020-12-26 08:08 UTC, KirillSmirnow commented on server/src/main/kotlin/org/itmodreamteam/myrest/server/error/converter/AccessDeniedExceptionToErrorsConverter.kt
> +        return userExceptionToErrorsConverter.convert(UserException("access-denied"))
Added caching of the errors list, which is  always the same

2020-12-28 12:19 UTC, Rznov approved these changes

2020-12-28 21:20 UTC, merged